### ISSUE TITLE
Small Issue while running paint.py

### ISSUE THREAD

**Issue by siddharth-kp** [myoluk/virtual-paint#1]
I am getting this error after excecuting paint.py

```
Traceback (most recent call last):
  File "E:\projects\virtual-paint\paint.py", line 22, in <module>
    hsvVal = np.load('hsvVal.npy')
  File "C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\numpy\lib\npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'hsvVal.npy'

Process finished with exit code 1

```

**Comment by siddharth-kp** [comment]
My fault, had a small issue with pycharm, now the file is getting saved in npy format.
